### ISSUE TITLE
If I already registered my subdomain.mozilla-iot.org DNS entry, how do I deploy a new gateway under this same subdomain?

### ISSUE THREAD

**Issue by ShotokuTech** [WebThingsIO/mozilla-iot.github.io#75]
Good day.
If I already registered my subdomain.mozilla-iot.org DNS entry, how do I deploy a new gateway under this same subdomain? Raspberry Pi 4B was just a temporary thing for me. Way too hot. I bought a new 3B, popped in a fresh flashed card. But what do I do to get back in under the subdomain I already registered before?
Thanks.

**Comment by mrstegeman** [comment]
When you do the initial setup, enter the same subdomain and email you did the first time. After doing so, you’ll be given the option to reclaim your domain.

**Comment by ShotokuTech** [comment]
Thanks.
